#!/usr/bin/env python3
"""
Parity test: tools/prompt_compiler.py (Python) vs Build_Retell_Prompt.js (JS).

Compares the Python port's output against a golden JSON fixture generated by
running the canonical JS source through tools/run_js_compiler.js against the
SAME input row.

Run:
    python tests/test_prompt_compiler_parity.py

Exits 0 if all diffs are empty. Prints first 30 divergences on failure.
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tools.prompt_compiler import compile  # noqa: E402

FIX = ROOT / 'tests' / 'fixtures' / 'prompt_compiler'
FIXED_TS = '2026-04-09T00:00:00.000Z'


def diff(a, b, path='') -> list[str]:
    out = []
    if type(a) is not type(b):
        if not (isinstance(a, (int, float)) and isinstance(b, (int, float))):
            out.append(f"{path}: TYPE {type(a).__name__} vs {type(b).__name__}")
            return out
    if isinstance(a, dict):
        keys_a = list(a.keys())
        keys_b = list(b.keys())
        if keys_a != keys_b:
            # Key order matters for byte-parity downstream
            only_a = [k for k in keys_a if k not in keys_b]
            only_b = [k for k in keys_b if k not in keys_a]
            if only_a or only_b:
                out.append(f"{path}: KEY MISMATCH only_in_python={only_a} only_in_js={only_b}")
            elif keys_a != keys_b:
                out.append(f"{path}: KEY ORDER differs\n  py:{keys_a}\n  js:{keys_b}")
        for k in keys_a:
            if k in b:
                out.extend(diff(a[k], b[k], f"{path}.{k}"))
    elif isinstance(a, list):
        if len(a) != len(b):
            out.append(f"{path}: LIST LEN {len(a)} vs {len(b)}")
        for i, (x, y) in enumerate(zip(a, b)):
            out.extend(diff(x, y, f"{path}[{i}]"))
    else:
        if a != b:
            if isinstance(a, str) and isinstance(b, str):
                # show first point of divergence
                idx = next((i for i, (ca, cb) in enumerate(zip(a, b)) if ca != cb), min(len(a), len(b)))
                ctx_a = repr(a[max(0, idx - 20):idx + 40])
                ctx_b = repr(b[max(0, idx - 20):idx + 40])
                out.append(f"{path}: STR at char {idx}\n  py: {ctx_a}\n  js: {ctx_b}")
            else:
                out.append(f"{path}: VAL {a!r} vs {b!r}")
    return out


def run_fixture(row_file: str, golden_file: str) -> int:
    with open(FIX / row_file, encoding='utf-8') as f:
        row = json.load(f)
    with open(FIX / golden_file, encoding='utf-8') as f:
        golden = json.load(f)
    py_out = compile(row, now_iso=FIXED_TS)
    diffs = diff(py_out, golden, '')
    if not diffs:
        print(f"  OK  {row_file} -> {golden_file}  ({len(json.dumps(py_out))} bytes)")
        return 0
    print(f"  FAIL {row_file} -> {golden_file}  ({len(diffs)} divergences)")
    for d in diffs[:30]:
        print(f"    {d}")
    if len(diffs) > 30:
        print(f"    ... and {len(diffs) - 30} more")
    return 1


def main() -> int:
    print("Prompt compiler parity test")
    print("=" * 60)
    rc = 0
    rc |= run_fixture('supabase_row_arctic_breeze.json', 'golden_arctic_breeze.json')
    rc |= run_fixture('supabase_row_fully_populated.json', 'golden_fully_populated.json')
    print("=" * 60)
    if rc == 0:
        print("PASS")
    else:
        print("FAIL")
    return rc


if __name__ == '__main__':
    sys.exit(main())
