#!/usr/bin/env python3
"""
test_post_call_analysis.py — Layer 1: Post-call analysis quality test.

Pulls the post-call analysis field definitions from the MASTER agent config
(tools/fixtures/post_call_analysis_config.json), generates an analysis prompt
for each transcript, and runs it via `claude -p` subprocess.

Compares actual is_lead / urgency / is_spam vs expected from scenarios.json.
Uses 5 parallel workers (ThreadPoolExecutor) — wall-clock ~30s vs 2+ min serial.

Usage:
  python tools/test_post_call_analysis.py              # run all 25 scenarios
  python tools/test_post_call_analysis.py --scenario 5 # run one scenario
  python tools/test_post_call_analysis.py --workers 5  # default parallelism

Required:
  tools/fixtures/scenarios.json
  tools/fixtures/post_call_analysis_config.json   (pulled from MASTER via Retell API)
  tools/fixtures/transcripts/scenario_{id}.txt    (generated by gen_transcripts.py)
"""
from __future__ import annotations
import argparse, json, re, subprocess, sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE        = Path(__file__).parent
FIXTURES    = HERE / "fixtures"
TRANSCRIPTS = FIXTURES / "transcripts"
SCENARIOS_F = FIXTURES / "scenarios.json"
PCA_CONFIG  = FIXTURES / "post_call_analysis_config.json"

PASS = "[PASS]"
FAIL = "[FAIL]"
INFO = "[INFO]"


# ── Load fixtures ──────────────────────────────────────────────────────────────

def load_scenarios() -> list[dict]:
    with open(SCENARIOS_F, encoding="utf-8") as f:
        return json.load(f)


def load_pca_config() -> list[dict]:
    with open(PCA_CONFIG, encoding="utf-8") as f:
        return json.load(f)


def load_transcript(scenario_id: int) -> str | None:
    path = TRANSCRIPTS / f"scenario_{scenario_id}.txt"
    if not path.exists():
        return None
    return path.read_text(encoding="utf-8")


# ── Build analysis prompt ──────────────────────────────────────────────────────

def build_analysis_prompt(transcript: str, pca_fields: list[dict]) -> str:
    """Build the prompt that replicates Retell's post-call analysis.

    Deliberately avoids brand-specific words (Sophie, HVAC, Syntharra) so that
    the claude -p subprocess does not trigger project-specific skills or context.
    """
    # Extract only custom fields (not system-presets)
    custom_fields = [f for f in pca_fields if f.get("type") != "system-presets"]

    field_specs = []
    for field in custom_fields:
        name  = field["name"]
        desc  = field.get("description", "")
        ftype = field.get("type", "")
        if ftype == "enum":
            choices = field.get("choices", [])
            spec = f'- "{name}" ({ftype}, one of: {choices}): {desc}'
        else:
            spec = f'- "{name}" ({ftype}): {desc}'
        field_specs.append(spec)

    fields_text = "\n".join(field_specs)
    field_names = [f["name"] for f in custom_fields]

    return f"""Classify the following customer service call transcript by filling in these fields:

{fields_text}

Instructions:
- Return ONLY a single JSON object with no extra text or markdown fences
- The JSON must contain exactly these keys: {field_names}
- For boolean fields: use true or false (JSON booleans, not strings)
- For enum fields: use exactly one of the listed choices as a string value

TRANSCRIPT:
{transcript}

JSON:"""


# ── Run one analysis ───────────────────────────────────────────────────────────

def run_analysis(scenario: dict, pca_fields: list[dict]) -> dict:
    """Run post-call analysis for one scenario. Returns result dict."""
    sid = scenario["id"]
    transcript = load_transcript(sid)
    if transcript is None:
        return {"id": sid, "passed": False, "error": "transcript missing — run gen_transcripts.py first"}

    prompt  = build_analysis_prompt(transcript, pca_fields)
    try:
        import platform
        on_windows = platform.system() == "Windows"
        # Run from a temp dir with a minimal CLAUDE.md.
        # Pass prompt via stdin (not as CLI arg) to bypass Windows 8191-char limit
        # and avoid the project CLAUDE.md loading skill context from the arg text.
        import os, tempfile, shutil
        tmpdir = tempfile.mkdtemp(prefix="pca_test_")
        with open(os.path.join(tmpdir, "CLAUDE.md"), "w", encoding="utf-8") as fh:
            fh.write("Output only valid JSON.")
        cmd = (["cmd", "/c", "claude"] if on_windows else ["claude"]) + [
            "-p", "--input-format", "text"
        ]
        result = subprocess.run(
            cmd, input=prompt, capture_output=True, text=True, timeout=120,
            encoding="utf-8", errors="replace", cwd=tmpdir
        )
        try:
            shutil.rmtree(tmpdir, ignore_errors=True)
        except Exception:
            pass
        raw = result.stdout.strip()
    except subprocess.TimeoutExpired:
        return {"id": sid, "passed": False, "error": "claude -p timed out"}
    except FileNotFoundError:
        return {"id": sid, "passed": False, "error": "`claude` CLI not found"}

    # Extract JSON from response (handles markdown code fences if present)
    # Try multiline nested match first, then simple non-nested
    json_match = re.search(r'\{[^{}]*\}', raw, re.DOTALL) or re.search(r'\{.*?\}', raw, re.DOTALL)
    if not json_match:
        return {"id": sid, "passed": False, "error": f"no JSON found in response: {raw[:200]}"}

    try:
        actual = json.loads(json_match.group())
    except json.JSONDecodeError as e:
        return {"id": sid, "passed": False, "error": f"JSON parse error: {e} in {raw[:200]}"}

    # Compare to expected
    expected = scenario["expected"]
    mismatches = []

    # is_lead: always checked — this is the primary routing field
    if "is_lead" in expected:
        if actual.get("is_lead") != expected["is_lead"]:
            mismatches.append(
                f"is_lead: expected={expected['is_lead']}, actual={actual.get('is_lead')}"
            )

    # urgency: only enforce when expected="emergency"
    #   - If expected=emergency: must be emergency (safety-critical)
    #   - If expected=none: must NOT be emergency (obvious non-call)
    #   - If expected=normal/high/low: not enforced — n8n routing only cares about emergency
    if "urgency" in expected:
        exp_urg = expected["urgency"]
        act_urg = actual.get("urgency", "none")
        if exp_urg == "emergency" and act_urg != "emergency":
            mismatches.append(
                f"urgency: expected={exp_urg} (emergency required), actual={act_urg}"
            )
        elif exp_urg == "none" and act_urg == "emergency":
            mismatches.append(
                f"urgency: expected={exp_urg} (emergency impossible), actual={act_urg}"
            )

    # is_spam: checked when explicitly expected
    if "is_spam" in expected:
        if actual.get("is_spam") != expected["is_spam"]:
            mismatches.append(
                f"is_spam: expected={expected['is_spam']}, actual={actual.get('is_spam')}"
            )

    return {
        "id":         sid,
        "name":       scenario["name"],
        "group":      scenario.get("group", "?"),
        "passed":     len(mismatches) == 0,
        "actual":     actual,
        "expected":   expected,
        "mismatches": mismatches,
    }


# ── Main ──────────────────────────────────────────────────────────────────────

def run(args: argparse.Namespace) -> int:
    scenarios  = load_scenarios()
    pca_fields = load_pca_config()

    if args.scenario:
        scenarios = [s for s in scenarios if s["id"] == args.scenario]
        if not scenarios:
            print(f"{FAIL} Scenario {args.scenario} not found")
            return 1

    # Check all transcripts exist before starting
    missing = [s["id"] for s in scenarios if not (TRANSCRIPTS / f"scenario_{s['id']}.txt").exists()]
    if missing:
        print(f"{FAIL} Missing transcripts for scenarios: {missing}")
        print(f"  Run: python tools/gen_transcripts.py")
        return 1

    workers = min(args.workers, len(scenarios))

    print(f"\n{'='*62}")
    print(f"  Post-Call Analysis Test — Layer 1")
    print(f"  Scenarios : {len(scenarios)}")
    print(f"  Workers   : {workers} parallel claude -p subprocesses")
    print(f"{'='*62}")

    results = []
    futures_map = {}

    with ThreadPoolExecutor(max_workers=workers) as pool:
        for sc in scenarios:
            future = pool.submit(run_analysis, sc, pca_fields)
            futures_map[future] = sc["id"]

        for future in as_completed(futures_map):
            res = future.result()
            results.append(res)
            sid = res["id"]
            if res.get("error"):
                print(f"  {FAIL} Scenario {sid}: ERROR — {res['error']}")
            elif res["passed"]:
                print(f"  {PASS} Scenario {sid} ({res.get('name', '')})")
            else:
                print(f"  {FAIL} Scenario {sid} ({res.get('name', '')})")
                for m in res.get("mismatches", []):
                    print(f"       {m}")
                print(f"       actual JSON: {json.dumps(res.get('actual', {}))}")

    results.sort(key=lambda r: r["id"])

    passed   = sum(1 for r in results if r["passed"])
    total    = len(results)
    pct      = passed / total * 100 if total else 0
    pass_thr = 95  # 24/25

    print(f"\n{'='*62}")
    print(f"  Result: {passed}/{total} scenarios passed ({pct:.0f}%)")

    failing = [r for r in results if not r["passed"]]
    if failing:
        print(f"\n  Failing scenarios:")
        for r in failing:
            print(f"    #{r['id']} {r.get('name', '')} — {r.get('mismatches') or r.get('error')}")

    if pct >= pass_thr:
        print(f"\n  {PASS} LAYER 1 PASSED ({pct:.0f}% >= {pass_thr}% threshold)")
    else:
        print(f"\n  {FAIL} LAYER 1 FAILED ({pct:.0f}% < {pass_thr}% threshold)")
        print(f"  Fix: update MASTER agent post_call_analysis_data prompt for failing scenarios")
        print(f"  (Max 10 words per fix. NEVER touch Sophie's conversation prompt.)")
    print(f"{'='*62}")

    return 0 if pct >= pass_thr else 1


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Post-call analysis quality test (Layer 1)")
    parser.add_argument("--scenario", type=int, help="Run one scenario by ID")
    parser.add_argument("--workers", type=int, default=5, help="Parallel workers (default: 5)")
    raise SystemExit(run(parser.parse_args()))
